spring:
  mail:
    host: smtp.gmail.com
    username: buensabor2024ll@gmail.com
    password: buensabor2024
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true