spring:
  mail:
    host: smtp.gmail.com
    username: buen.sabor424gmail.com
    password: buensabor123
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true